"use client"
import Navbar from "../components/navbar";
import "../styles/globals.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  // Layouts must accept a children prop.
  // This will be populated with nested layouts or pages
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <div className="min-h-screen min-w-full grid grid-cols-4 gap-6">
      <div className="col-span-1 justify-self-end mt-12">
        <Navbar />
      </div>
      <div className="col-span-3 mt-12 ml-6 ">{children}</div>
    </div>
    </html>
  )
}
