import Navbar from "../components/navbar";
import "../styles/globals.css"
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  // Layouts must accept a children prop.
  // This will be populated with nested layouts or pages
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <div className="h-screen w-full grid grid-cols-4 gap-6 overflow-auto">
      <div className="justify-self-end ol-span-1 mt-12">
        <Navbar />
      </div>
      <div className="col-span-3 mt-12 ml-6 overflow-auto">{children}</div>
    </div>
    </html>
  )
}
